// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StanzaBonanza.DataAccess.DbContexts;

#nullable disable

namespace StanzaBonanza.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230324013312_AddIndexes1")]
    partial class AddIndexes1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StanzaBonanza.Models.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("Date");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "Amy",
                            RegisteredDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "Bella",
                            RegisteredDate = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StanzaBonanza.Models.Models.Poem", b =>
                {
                    b.Property<int>("PoemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoemId"));

                    b.Property<int>("AuthorCreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PoemId");

                    b.ToTable("Poems");

                    b.HasData(
                        new
                        {
                            PoemId = 1,
                            AuthorCreatorId = 1,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Foo"
                        },
                        new
                        {
                            PoemId = 2,
                            AuthorCreatorId = 2,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac laoreet mauris. Aliquam erat volutpat.",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bar"
                        },
                        new
                        {
                            PoemId = 3,
                            AuthorCreatorId = 2,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac laoreet mauris. Aliquam erat volutpat. Duis id metus enim. Aenean scelerisque eros nibh",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Baz"
                        });
                });

            modelBuilder.Entity("StanzaBonanza.Models.Models.Poem_Author", b =>
                {
                    b.Property<int>("Poem_AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Poem_AuthorId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PoemId")
                        .HasColumnType("int");

                    b.HasKey("Poem_AuthorId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PoemId");

                    b.ToTable("Poems_Authors");

                    b.HasData(
                        new
                        {
                            PoemAuthorId = 1,
                            AuthorId = 1,
                            PoemId = 1
                        },
                        new
                        {
                            PoemAuthorId = 2,
                            AuthorId = 2,
                            PoemId = 1
                        },
                        new
                        {
                            PoemAuthorId = 3,
                            AuthorId = 2,
                            PoemId = 2
                        },
                        new
                        {
                            PoemAuthorId = 4,
                            AuthorId = 1,
                            PoemId = 3
                        },
                        new
                        {
                            PoemAuthorId = 5,
                            AuthorId = 2,
                            PoemId = 3
                        });
                });

            modelBuilder.Entity("StanzaBonanza.Models.Models.Poem_Author", b =>
                {
                    b.HasOne("StanzaBonanza.Models.Models.Author", "Author")
                        .WithMany("Poem_Authors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StanzaBonanza.Models.Models.Poem", "Poem")
                        .WithMany("Poem_Authors")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Poem");
                });

            modelBuilder.Entity("StanzaBonanza.Models.Models.Author", b =>
                {
                    b.Navigation("Poem_Authors");
                });

            modelBuilder.Entity("StanzaBonanza.Models.Models.Poem", b =>
                {
                    b.Navigation("Poem_Authors");
                });
#pragma warning restore 612, 618
        }
    }
}
